In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df.to_csv("student_performance.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [3]:
df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [4]:
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [5]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(12, 4)

In [6]:
print(df.columns)

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [7]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [8]:
X = df[['Study_Hours','Attendance','Assignments']]

y = df['Marks']

print("Features")
print(X)

print("\nLabel")
print(y)

Features
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

X_train Shape: (9, 3)
X_test Shape: (3, 3)
y_train Shape: (9,)
y_test Shape: (3,)

In [10]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Slope / Coefficients:")
print(model.coef_)

print("\nIntercept:")
print(model.intercept_)

Slope / Coefficients:
[ 3.45487968  1.34491979 -2.40274064]

Intercept:
-48.100601604278054

In [11]:
new_data = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

predictions = model.predict(new_data)

result = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10],
    "Predicted Marks":predictions
})

result

   Study_Hours  Attendance  Assignments  Predicted Marks
0            5          80            5        64.753676
1            8          90            8        81.359291
2           12          95           10        97.097928

In [12]:
y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks": y_test.values,
    "Predicted Marks": y_pred
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

comparison

   Actual Marks  Predicted Marks  Difference
0            92        92.011029    0.011029
1            88        88.269051    0.269051
2            35        31.243984    3.756016

In [13]:
highest_error = comparison.loc[
    comparison["Difference"].idxmax()
]

print(highest_error)

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 2, dtype: float64

In [14]:
mae = mean_absolute_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)

print("R2 Score:", r2)

Mean Absolute Error: 1.3453654188948245
R2 Score: 0.9929962957709836

In [15]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [16]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=["Assignments"],
    title="Attendance vs Marks"
)

fig.show()

In [17]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Marks",
    title="Assignments vs Marks"
)

fig.show()

In [18]:
fig = px.scatter(
    x=y_test,
    y=y_pred,
    labels={
        "x":"Actual Marks",
        "y":"Predicted Marks"
    },
    title="Actual vs Predicted Marks"
)

fig.show()

In [19]:
future = pd.DataFrame({
    "Study_Hours": list(range(1,16)),
    "Attendance": [80]*15,
    "Assignments": [5]*15
})

future["Predicted Marks"] = model.predict(
    future
)

fig = px.line(
    future,
    x="Study_Hours",
    y="Predicted Marks",
    title="Predicted Marks Trend"
)

fig.show()

In [20]:
print("Assignment Completed Successfully")

Assignment Completed Successfully